### PR TITLE
updated  readme [ci skip]

### PR DESCRIPTION
**Pull request by ferdinandrosario**
updated readme for patch version

### CODE REVIEW

**Comment by peterhellberg** [comment]
I’ll update the README again when I’ve managed to get 2.2.2 to build.

**Comment by ferdinandrosario** [comment]
OK :+1:

**Comment by ferdinandrosario** [comment]
Hi @peterhellberg jruby-1.7.21 is the latest stable so could you update?

**Comment by peterhellberg** [comment]
No, 1.7.20 is the latest binary on Travis-CI. I’ll change it when they release new builds.

I’m also considering changing the `gem.required_ruby_version` from 1.9.3 to 2.0.0 since 1.9.x has reached end of life.

**Comment by ferdinandrosario** [comment]
That great. this will encourage people to upgrade their ruby and aviod unwanted problems. Thanks for the good work :+1:  :heart:

**Pull request merged**
