### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by gogainda** [comment]
@peterhellberg pls review/merge

**Comment by peterhellberg** [comment]
@gogainda Is there a reason to build against head instead of latest stable?

**Comment by gogainda** [comment]
@peterhellberg truffleruby stable releases not quite often(every 3 months if I am not mistaken), so some of the fixes may be missing which are already available on the head version. From the quality perspective stable and head are the same, so it's quite safe to treat the head version as a "to be released" stable one.

**Comment by peterhellberg** [comment]
Ok

**Pull request merged**
